on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build_container:
    runs-on: ubuntu-latest
    name: "buildContainer"
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}
      - name: "buildDockerfile"
        run: |
          docker build -t ubuntucloudcamp:1.0.0 .
      - name: "deployment"
        run: |
          docker tag ubuntucloudcamp:1.0.0 ghcr.io/gitronald2023/ubuntucloudcamp:latest
          docker push ghcr.io/gitronald2023/ubuntucloudcamp:latest
        
